DROP TABLE refresh_sessions;
DROP TABLE "order";
DROP TABLE comment;
DROP TABLE coach_service;
DROP TABLE abonement_service;
DROP TABLE coach;
DROP TABLE "user";
DROP TABLE service;
DROP TABLE abonement;